flyway.user=user_database_recipe
flyway.password=user_database_1975
flyway.schemas=public # Vamos tentar criar tudo no schema 'public' inicialmente
flyway.url=jdbc:postgresql://localhost:5432/database_user
flyway.locations=filesystem:db/migration