spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/database_user
spring.datasource.username=user_database_recipe
spring.datasource.password=user_database_1975
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.flywaydb=DEBUG